name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # (valgfritt) pre-build steg her om du trenger

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: NikoBrokk            # <-- sett til token-eierens brukernavn
        run: |
          set -e
          SPACE_URL="https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/Gabrielsen-AI/RAG-Asker-Fotball"
          TARGET_BRANCH="main"              # bruk "master" hvis Space har master

          git remote add space "${SPACE_URL}"
          git fetch space "${TARGET_BRANCH}" || true
          git push --force-with-lease space HEAD:${TARGET_BRANCH}
